# Generated by Django 4.1.4 on 2022-12-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_project_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('1', 'Not Submitted'), ('2', 'Submitted')], default='2', max_length=20),
        ),
    ]
