# Generated by Django 4.1.4 on 2022-12-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_empleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleave',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approve'), ('Rejected', 'Reject')], default='Pending', max_length=20),
        ),
    ]
